export const RESOURCE_REQUESTED = "RESOURCE_REQUESTED";
export type RESOURCE_REQUESTED = typeof RESOURCE_REQUESTED;

export const RESOURCE_SUCCEEDED = "RESOURCE_SUCCEEDED";
export type RESOURCE_SUCCEEDED = typeof RESOURCE_SUCCEEDED;

export const RESOURCE_FAILED = "RESOURCE_FAILED";
export type RESOURCE_FAILED = typeof RESOURCE_FAILED;

export const RESOURCE_INIT = "RESOURCE_INIT";
export type RESOURCE_INIT = typeof RESOURCE_INIT;
